version: '3'

services:
  php:
    build: .
    ports:
      - "3004:80"
    depends_on:
      - mysql-db
    restart: unless-stopped
    image: "nheek/shareme:latest"

  mysql-db:
    image: mysql:latest
    restart: unless-stopped
    ports:
      - "4004:3306"
    env_file:
      - .env
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - mysql_db_data:/var/lib/mysql
      - .sql_data:/docker-entrypoint-initdb.d/
      - .custom_sql_settings:/etc/mysql/conf.d/

volumes:
  mysql_db_data: